stages:
  training:
    cmd: uv run main.py
    deps:
    - data_harvesting/actor.py
    - data_harvesting/collector.py
    - data_harvesting/critic.py
    - data_harvesting/environment.py
    - data_harvesting/optimization.py
    - data_harvesting/replay.py
    - main.py