[project]
name = "data-harvesting-workspace"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = []

[tool.uv]
package = false

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu128", marker = "sys_platform == 'linux' or sys_platform == 'win32'" }
torchvision = { index = "pytorch-cu128", marker = "sys_platform == 'linux' or sys_platform == 'win32'" }
flex-marl = { workspace = true }
rl-core = { workspace = true }
validation-core = { workspace = true }
d-atc = { workspace = true }
data-harvesting = { workspace = true }
small-talk = { workspace = true }

[tool.uv.workspace]
members = [
    "packages/*",
    "projects/*",
]

[tool.pytest.ini_options]
addopts = "--import-mode=importlib"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "flex-marl",
    "rl-core",
    "validation-core",
    "d-atc",
    "data-harvesting",
    "small-talk"
]
