environment:
  algorithm_iteration_interval: 0.5
  num_drones: 4
  num_sensors: 24
  scenario_size: 100.0
  max_episode_length: 500
  max_seconds_stalled: 30
  communication_range: 20.0
  state_num_closest_sensors: 2
  state_num_closest_drones: 2
  state_mode: relative
  id_on_state: true
  min_sensor_priority: 0.1
  max_sensor_priority: 1.0
  full_random_drone_position: false
  reward: punish
  speed_action: true
  end_when_all_collected: true
actor:
  share_parameters: true
  network_depth: 2
  network_width: 256
  activation_function: Tanh
  centralized: false
training:
  total_timesteps: 10000
  exploration_sigma_init: 0.9
  exploration_sigma_end: 0.1
  exploration_annealing_steps: 500000
  batch_size: 256
critic:
  network_depth: 2
  network_width: 256
  activation_function: Tanh
  share_parameters: true
  centralized: true
collector:
  num_collectors: 4
  frames_per_batch: 1000
  async_collector: true
replay_buffer:
  buffer_size: 1000000
  prefetch: 0
  buffer_device: cpu
optimization:
  gamma: 0.99
  lr: 0.0003
  tau: 0.005
  num_optimizer_steps: 5
