environment:
  algorithm_iteration_interval: 2.0
  num_drones: 2
  num_sensors: 12
  scenario_size: 100
  max_episode_length: 500
  max_seconds_stalled: 30
  communication_range: 20.0
  state_num_closest_sensors: 12
  state_num_closest_drones: 1
  state_mode: relative
  id_on_state: true
  min_sensor_priority: 1.0
  max_sensor_priority: 1.0
  full_random_drone_position: false
  reward: punish
  speed_action: true
  end_when_all_collected: false
actor:
  share_parameters: true
  network_depth: 2
  network_width: 256
  activation_function: Tanh
  centralized: false
training:
  total_timesteps: 50000000
  exploration_sigma_init: 0.1
  exploration_sigma_end: 0.1
  exploration_annealing_steps: 500000
  batch_size: 256
critic:
  network_depth: 2
  network_width: 512
  activation_function: Tanh
  share_parameters: true
  centralized: true
collector:
  num_collectors: 4
  frames_per_batch: 1000
  async_collector: true
replay_buffer:
  buffer_size: 1000000
  prefetch: 12
  buffer_device: gpu
optimization:
  gamma: 0.99
  lr: 1e-05
  tau: 0.005
  num_optimizer_steps: 1
  grad_clip: 0
